apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app":"writer-go-b"},"name":"writer-go-b","namespace":"proyecto2"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"writer-go-b"}},"template":{"metadata":{"labels":{"app":"writer-go-b"}},"spec":{"containers":[{"env":[{"name":"KAFKA_BROKER","value":"kafka-service:29092"},{"name":"KAFKA_TOPIC","value":"ventas"},{"name":"GRPC_PORT","value":"50051"}],"image":"writer-go-b:latest","imagePullPolicy":"IfNotPresent","livenessProbe":{"initialDelaySeconds":10,"periodSeconds":10,"tcpSocket":{"port":50051}},"name":"writer-go-b","ports":[{"containerPort":50051}],"readinessProbe":{"initialDelaySeconds":3,"periodSeconds":5,"tcpSocket":{"port":50051}},"resources":{"limits":{"cpu":"500m","memory":"256Mi"},"requests":{"cpu":"50m","memory":"64Mi"}}}]}}}}
  creationTimestamp: "2025-12-25T01:08:43Z"
  generation: 2
  labels:
    app: writer-go-b
  name: writer-go-b
  namespace: proyecto2
  resourceVersion: "12809"
  uid: 4946e730-6a61-43b8-b193-248776d4bfd4
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: writer-go-b
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2025-12-24T19:44:50-06:00"
      creationTimestamp: null
      labels:
        app: writer-go-b
    spec:
      containers:
      - env:
        - name: KAFKA_BROKER
          value: kafka-service:29092
        - name: KAFKA_TOPIC
          value: ventas
        - name: GRPC_PORT
          value: "50051"
        image: writer-go-b:latest
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 50051
          timeoutSeconds: 1
        name: writer-go-b
        ports:
        - containerPort: 50051
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          initialDelaySeconds: 3
          periodSeconds: 5
          successThreshold: 1
          tcpSocket:
            port: 50051
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 256Mi
          requests:
            cpu: 50m
            memory: 64Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-12-25T01:08:48Z"
    lastUpdateTime: "2025-12-25T01:08:48Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-12-25T01:08:43Z"
    lastUpdateTime: "2025-12-25T01:44:55Z"
    message: ReplicaSet "writer-go-b-5d48dccc5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
